#!/usr/bin/env python3
"""
Migrate specific Purchase Orders and Sale Orders from an Odoo 16 database
to an Odoo 19 database, using Odoo's XML-RPC API on both ends (no direct
DB access needed, works across versions).

WHY XML-RPC AND NOT RAW SQL / A DB DUMP:
Purchase/sale orders reference partners, products, taxes, UoMs, and
users - all of which have DIFFERENT internal IDs in the two databases.
Copying rows directly would silently point at the wrong partner/product
in v19. This script instead re-creates each order through Odoo's own API,
resolving each reference by a stable business key (partner: email/VAT/name,
product: default_code/name) so it lands on the correct v19 record, or is
clearly reported as unmatched if it can't be resolved automatically.

WHAT GETS MIGRATED PER ORDER:
    Partner/vendor, currency, order date, expected arrival (POs) /
    reference (SOs), notes, every order line (product, qty, price, UoM,
    taxes - each resolved to its v19 equivalent), and every file
    attachment on the record (quotes, scanned documents, etc. - copied
    by content, not by reference, since attachment IDs also differ
    between the two databases).

WHAT THIS DOES NOT DO:
- Delivery Notes (WH/OUT/..., WH/RET/...) are not recreated directly.
  They're generated by Odoo automatically as a side effect of confirming
  a Sale Order or receiving a Purchase Order - trying to fabricate them
  standalone would produce pickings disconnected from real stock moves.
  Once the SOs/POs below are migrated and confirmed/received in v19 in
  the same way they were in v16, the matching delivery notes will be
  created by Odoo itself.
- It does not delete or modify anything in Odoo 16 (source only, read-only).
- It skips (does not duplicate) any order that already exists in v19 by
  the same name - safe to re-run.

USAGE:
    1. Fill in the CONFIG section below (or set the environment variables
       it reads from).
    2. Test a single record first, dry-run (no changes made):
           python3 migrate_po_so.py --only P01202
    3. Once that output looks correct, apply it for real - still just
       the one record:
           python3 migrate_po_so.py --only P01202 --apply
    4. Check the result in Odoo 19's UI, then run the full batch:
           python3 migrate_po_so.py              # dry-run, all records
           python3 migrate_po_so.py --apply       # actually create them

REQUIREMENTS:
    Python 3 standard library only (xmlrpc.client) - nothing to pip install.
"""

import argparse
import sys
import xmlrpc.client
from collections import defaultdict

# ============================================================================
# CONFIG - fill these in, or export as environment variables of the same
# name (os.environ) and remove the literal values below.
# ============================================================================

SOURCE = {
    "url": "https://odoo.aala-tech.com",   # Odoo 16 - adjust host/port
    "db": "odoo",                     # Odoo 16 database name
    "username": "imran.sarwar@aala-tech.com",
    "password": "123",          # or an API key
}

TARGET = {
    "url": "https://erp-odoo.aala-tech.com",   # Odoo 19 - adjust host/port
    "db": "aala_tech_production",     # Odoo 19 database name
    "username": "imran.sarwar@aala-tech.com",
    "password": "123",  # or an API key
}

# Record names to migrate - taken directly from Odoo_16_Updated_Entry_Details.xlsx
PO_NAMES = [
    # "P01199",
]

# "S00649 - Revision" in the sheet is a note, not a literal record name -
# the real order is S00649. Adjust if that's wrong.
SO_NAMES = [
    "S00649", "S00687", "S00688", "S00689", "S00690", "S00691",
]


# ============================================================================
# XML-RPC helpers
# ============================================================================

class OdooConnection:
    """Thin wrapper around Odoo's XML-RPC API (works against any Odoo
    version - 16 and 19 both expose the same /xmlrpc/2/* endpoints)."""

    def __init__(self, url, db, username, password, label):
        self.url = url
        self.db = db
        self.label = label
        common = xmlrpc.client.ServerProxy(f"{url}/xmlrpc/2/common")
        self.uid = common.authenticate(db, username, password, {})
        if not self.uid:
            raise RuntimeError(
                f"[{label}] Authentication failed for user {username!r} "
                f"on db {db!r} at {url}"
            )
        self.password = password
        self.models = xmlrpc.client.ServerProxy(f"{url}/xmlrpc/2/object")

    def execute(self, model, method, *args, **kwargs):
        return self.models.execute_kw(
            self.db, self.uid, self.password, model, method, list(args), kwargs
        )

    def search_read(self, model, domain, fields, **kwargs):
        return self.execute(model, "search_read", domain, fields, **kwargs)

    def search(self, model, domain, **kwargs):
        return self.execute(model, "search", domain, **kwargs)

    def get_field_names(self, model):
        """Cached set of real field names on this connection for a given
        model. Used to drop fields that don't exist on this specific Odoo
        version instead of failing outright - field names occasionally
        differ between versions (e.g. purchase.order's notes/note field),
        and this makes the script resilient to that without needing to
        hardcode every possible variant."""
        if not hasattr(self, "_field_cache"):
            self._field_cache = {}
        if model not in self._field_cache:
            fields = self.execute(model, "fields_get", [], {"attributes": []})
            self._field_cache[model] = set(fields.keys())
        return self._field_cache[model]

    def create(self, model, vals):
        known = self.get_field_names(model)
        safe_vals = {}
        dropped = []
        for key, value in vals.items():
            if key not in known:
                dropped.append(key)
                continue
            # Also filter fields inside one2many command tuples like
            # order_line: [(0, 0, {...}), ...] - check each line's inner
            # dict against the actual line model's field list too, since
            # field names can differ there independently of the header
            # (e.g. product_uom vs product_uom_id, taxes_id vs tax_ids).
            if key == "order_line" and isinstance(value, list):
                line_model = ("purchase.order.line" if model == "purchase.order"
                              else "sale.order.line")
                line_known = self.get_field_names(line_model)
                new_lines = []
                for cmd in value:
                    if isinstance(cmd, (list, tuple)) and len(cmd) == 3 and cmd[0] == 0:
                        line_vals = cmd[2]
                        safe_line_vals = {}
                        for lkey, lvalue in line_vals.items():
                            if lkey in line_known:
                                safe_line_vals[lkey] = lvalue
                            else:
                                dropped.append(f"order_line.{lkey}")
                        new_lines.append((0, 0, safe_line_vals))
                    else:
                        new_lines.append(cmd)
                safe_vals[key] = new_lines
            else:
                safe_vals[key] = value
        if dropped:
            print(f"    [WARN] {model}: dropping field(s) not present on "
                  f"target - {', '.join(dropped)}")
        return self.execute(model, "create", safe_vals)


# ============================================================================
# Cross-database matching (partner / product / uom / tax)
# ============================================================================

class RecordMatcher:
    """Resolves a v16 record (partner, product, uom, tax) to its v19
    equivalent by business key, caching lookups. Anything it can't match
    is recorded in .unmatched for the final report - never silently
    guesses."""

    def __init__(self, target: OdooConnection):
        self.target = target
        self.partner_cache = {}
        self.product_cache = {}
        self.uom_cache = {}
        self.tax_cache = {}
        self.currency_cache = {}
        self.unmatched = defaultdict(set)

    def match_partner(self, src_partner):
        """src_partner: dict with at least 'id' and 'name'; ideally also
        'email' and 'vat' from a search_read on res.partner."""
        key = src_partner["id"]
        if key in self.partner_cache:
            return self.partner_cache[key]

        target_id = None
        vat = (src_partner.get("vat") or "").strip()
        email = (src_partner.get("email") or "").strip()
        name = (src_partner.get("name") or "").strip()

        if vat:
            found = self.target.search("res.partner", [["vat", "=", vat]], limit=1)
            if found:
                target_id = found[0]
        if not target_id and email:
            found = self.target.search("res.partner", [["email", "=", email]], limit=1)
            if found:
                target_id = found[0]
        if not target_id and name:
            found = self.target.search("res.partner", [["name", "=", name]], limit=1)
            if found:
                target_id = found[0]

        if target_id:
            # Found - leave the existing target partner exactly as-is.
            # Never overwrite it, even if source data has since changed -
            # whatever is already in v19 is treated as authoritative.
            self.partner_cache[key] = target_id
            return target_id

        # Not found - create it in the target instead of failing the
        # whole order over a missing vendor/customer.
        partner_vals = {
            "name": name,
            "email": email or False,
            "vat": vat or False,
            "phone": src_partner.get("phone") or False,
            "mobile": src_partner.get("mobile") or False,
            "street": src_partner.get("street") or False,
            "city": src_partner.get("city") or False,
        }
        partner_vals = {k: v for k, v in partner_vals.items() if v}
        target_id = self.target.create("res.partner", partner_vals)
        print(f"    [CREATE] partner {name!r} created in target as id={target_id}")

        self.partner_cache[key] = target_id
        return target_id

    def match_product(self, src_product):
        """src_product: dict with 'id', 'default_code', 'name'."""
        key = src_product["id"]
        if key in self.product_cache:
            return self.product_cache[key]

        target_id = None
        code = (src_product.get("default_code") or "").strip()
        name = (src_product.get("name") or "").strip()

        if code:
            found = self.target.search(
                "product.product", [["default_code", "=", code]], limit=1
            )
            if found:
                target_id = found[0]
        if not target_id and name:
            found = self.target.search(
                "product.product", [["name", "=", name]], limit=1
            )
            if found:
                target_id = found[0]

        if target_id:
            # Found - leave the existing target product exactly as-is,
            # same policy as vendors/customers: never overwrite it.
            self.product_cache[key] = target_id
            return target_id

        # Not found - create it in the target instead of failing the
        # order over a missing product. Kept intentionally minimal
        # (name + default_code only) since we don't have enough source
        # data here to safely set accounting/costing fields - those
        # should be reviewed and filled in manually in v19 afterward.
        product_vals = {"name": name}
        if code:
            product_vals["default_code"] = code
        target_id = self.target.create("product.product", product_vals)
        print(f"    [CREATE] product {name!r} created in target as id={target_id}")

        self.product_cache[key] = target_id
        return target_id

    def match_uom(self, src_uom_name):
        if src_uom_name in self.uom_cache:
            return self.uom_cache[src_uom_name]
        found = self.target.search("uom.uom", [["name", "=", src_uom_name]], limit=1)
        target_id = found[0] if found else None
        self.uom_cache[src_uom_name] = target_id
        if not target_id:
            self.unmatched["uom"].add(src_uom_name)
        return target_id

    def match_tax(self, src_tax_name, type_tax_use):
        cache_key = (src_tax_name, type_tax_use)
        if cache_key in self.tax_cache:
            return self.tax_cache[cache_key]
        found = self.target.search(
            "account.tax",
            [["name", "=", src_tax_name], ["type_tax_use", "=", type_tax_use]],
            limit=1,
        )
        target_id = found[0] if found else None
        self.tax_cache[cache_key] = target_id
        if not target_id:
            self.unmatched["tax"].add(f"{src_tax_name} ({type_tax_use})")
        return target_id

    def match_currency(self, src_currency_name):
        """Currencies are matched by their 3-letter ISO code (e.g. 'SAR',
        'USD', 'EUR', 'AED') - this code is stable and identical across
        any two Odoo databases, so no fuzzy matching is needed here."""
        if src_currency_name in self.currency_cache:
            return self.currency_cache[src_currency_name]
        found = self.target.search(
            "res.currency", [["name", "=", src_currency_name]], limit=1
        )
        target_id = found[0] if found else None
        self.currency_cache[src_currency_name] = target_id
        if not target_id:
            self.unmatched["currency"].add(src_currency_name)
        return target_id


def _copy_attachments(source, target, res_model, source_res_id, target_res_id, label):
    """Copy every file attachment from a source record to its newly
    created target record. Attachments aren't referenced by business key
    the way partners/products are - they're just files - so we copy them
    by name + raw content directly."""
    attachments = source.search_read(
        "ir.attachment",
        [["res_model", "=", res_model], ["res_id", "=", source_res_id]],
        ["name", "datas", "mimetype"],
    )
    for att in attachments:
        if not att.get("datas"):
            continue  # empty/placeholder attachment, nothing to copy
        target.create("ir.attachment", {
            "name": att["name"],
            "datas": att["datas"],
            "mimetype": att.get("mimetype") or False,
            "res_model": res_model,
            "res_id": target_res_id,
        })
    if attachments:
        print(f"    -> copied {len(attachments)} attachment(s) for {label}")


# ============================================================================
# Purchase Orders
# ============================================================================

def migrate_purchase_orders(source, target, matcher, names, apply_changes):
    print("\n" + "=" * 70)
    print("PURCHASE ORDERS")
    print("=" * 70)

    orders = source.search_read(
        "purchase.order",
        [["name", "in", names]],
        [
            "name", "partner_id", "date_order", "date_planned", "partner_ref",
            "notes", "order_line", "currency_id",
        ],
    )
    found_names = {o["name"] for o in orders}
    for missing in set(names) - found_names:
        print(f"  [SKIP] {missing}: not found in source (Odoo 16)")

    for order in orders:
        name = order["name"]

        existing = target.search("purchase.order", [["name", "=", name]], limit=1)
        if existing:
            print(f"  [SKIP] {name}: already exists in target (id={existing[0]})")
            continue

        partner = source.search_read(
            "res.partner", [["id", "=", order["partner_id"][0]]],
            ["name", "email", "vat", "phone", "mobile", "street", "city"],
        )[0]
        target_partner_id = matcher.match_partner(partner)
        if not target_partner_id:
            print(f"  [FAIL] {name}: vendor {partner['name']!r} not found in target - skipped")
            continue

        target_currency_id = None
        if order.get("currency_id"):
            currency = source.search_read(
                "res.currency", [["id", "=", order["currency_id"][0]]], ["name"]
            )[0]
            target_currency_id = matcher.match_currency(currency["name"])
            if not target_currency_id:
                print(f"  [FAIL] {name}: currency {currency['name']!r} not found in target - skipped")
                continue

        lines = source.search_read(
            "purchase.order.line",
            [["id", "in", order["order_line"]]],
            ["product_id", "name", "product_qty", "price_unit",
             "product_uom", "taxes_id", "display_type"],
        )

        line_vals = []
        line_error = False
        for line in lines:
            if line.get("display_type") in ("line_section", "line_note"):
                # Real section header or free-text note from source -
                # preserve its actual type instead of collapsing both
                # into "note". Neither needs a product or quantity at all.
                line_vals.append((0, 0, {
                    "name": line["name"],
                    "display_type": line["display_type"],
                }))
                continue

            if not line["product_id"]:
                # No display_type set, but also no product - treat as a
                # plain note as a fallback (source data oddity).
                line_vals.append((0, 0, {
                    "name": line["name"],
                    "display_type": "line_note",
                }))
                continue

            if not line.get("product_qty"):
                # Some source lines have no quantity set at all (not even
                # 0.0 - a genuine missing value) - v19 rejects these
                # outright. Skip just this one line rather than crashing
                # the whole order, and flag it clearly for manual review.
                print(f"  [WARN] {name}: line {line['name']!r} has no "
                      f"quantity in source - line skipped, order still created")
                continue

            product = source.search_read(
                "product.product", [["id", "=", line["product_id"][0]]],
                ["default_code", "name"],
            )[0]
            target_product_id = matcher.match_product(product)
            if not target_product_id:
                print(f"  [FAIL] {name}: product {product['name']!r} not found in target")
                line_error = True
                continue

            uom = source.search_read(
                "uom.uom", [["id", "=", line["product_uom"][0]]], ["name"]
            )[0]
            target_uom_id = matcher.match_uom(uom["name"])

            # Source (v16) field is 'taxes_id' - correct, unrelated to target.
            target_tax_ids = []
            if line["taxes_id"]:
                taxes = source.search_read(
                    "account.tax", [["id", "in", line["taxes_id"]]],
                    ["name", "type_tax_use"],
                )
                for tax in taxes:
                    t_id = matcher.match_tax(tax["name"], tax["type_tax_use"])
                    if t_id:
                        target_tax_ids.append(t_id)

            # Target (v19) field is 'tax_ids' on purchase.order.line, not
            # 'taxes_id' - confirmed against the live server's fields_get.
            line_vals.append((0, 0, {
                "name": line["name"],
                "product_id": target_product_id,
                "product_qty": line["product_qty"],
                "price_unit": line["price_unit"],
                "product_uom_id": target_uom_id or False,
                "tax_ids": [(6, 0, target_tax_ids)],
            }))

        if line_error:
            print(f"  [FAIL] {name}: skipped due to unmatched product(s) above")
            continue

        vals = {
            "partner_id": target_partner_id,
            "partner_ref": order.get("partner_ref") or "",
            "date_order": order["date_order"],
            "date_planned": order.get("date_planned") or False,
            "note": order.get("notes") or "",
        }
        if target_currency_id:
            vals["currency_id"] = target_currency_id

        if not apply_changes:
            print(f"  [DRY-RUN] Would create PO {name} "
                  f"(vendor={partner['name']}, {len(line_vals)} line(s))")
            continue

        # Create the header first (no lines yet), then add lines one at a
        # time. If Odoo rejects a specific line (e.g. a data quirk that
        # slipped past our own checks), only that single line is skipped
        # - the order itself, and every other valid line, still goes
        # through instead of the whole order being lost.
        new_id = target.create("purchase.order", vals)
        target.execute("purchase.order", "write", [new_id], {"name": name})

        added, skipped = 0, 0
        for lv in line_vals:
            try:
                target.execute("purchase.order", "write", [new_id], {"order_line": [lv]})
                added += 1
            except xmlrpc.client.Fault as e:
                skipped += 1
                reason = e.faultString.splitlines()[-1] if e.faultString else str(e)
                print(f"  [WARN] {name}: line skipped - {reason}")
                print(f"    Line data: {lv}")

        _copy_attachments(source, target, "purchase.order", order["id"], new_id, name)
        status = f"{added} line(s) added" + (f", {skipped} skipped" if skipped else "")
        print(f"  [OK] {name}: created in target as id={new_id} ({status})")



# ============================================================================
# Sale Orders
# ============================================================================

def migrate_sale_orders(source, target, matcher, names, apply_changes):
    print("\n" + "=" * 70)
    print("SALE ORDERS")
    print("=" * 70)

    orders = source.search_read(
        "sale.order",
        [["name", "in", names]],
        ["name", "partner_id", "date_order", "client_order_ref",
         "note", "order_line", "currency_id"],
    )
    found_names = {o["name"] for o in orders}
    for missing in set(names) - found_names:
        print(f"  [SKIP] {missing}: not found in source (Odoo 16)")

    for order in orders:
        name = order["name"]

        existing = target.search("sale.order", [["name", "=", name]], limit=1)
        if existing:
            print(f"  [SKIP] {name}: already exists in target (id={existing[0]})")
            continue

        partner = source.search_read(
            "res.partner", [["id", "=", order["partner_id"][0]]],
            ["name", "email", "vat", "phone", "mobile", "street", "city"],
        )[0]
        target_partner_id = matcher.match_partner(partner)
        if not target_partner_id:
            print(f"  [FAIL] {name}: customer {partner['name']!r} not found in target - skipped")
            continue

        target_currency_id = None
        if order.get("currency_id"):
            currency = source.search_read(
                "res.currency", [["id", "=", order["currency_id"][0]]], ["name"]
            )[0]
            target_currency_id = matcher.match_currency(currency["name"])
            if not target_currency_id:
                print(f"  [FAIL] {name}: currency {currency['name']!r} not found in target - skipped")
                continue

        lines = source.search_read(
            "sale.order.line",
            [["id", "in", order["order_line"]]],
            ["product_id", "name", "product_uom_qty", "price_unit",
             "product_uom", "tax_id", "display_type"],
        )

        line_vals = []
        line_error = False
        for line in lines:
            if line.get("display_type") in ("line_section", "line_note"):
                line_vals.append((0, 0, {
                    "name": line["name"],
                    "display_type": line["display_type"],
                }))
                continue

            if not line["product_id"]:
                line_vals.append((0, 0, {
                    "name": line["name"],
                    "display_type": "line_note",
                }))
                continue

            if not line.get("product_uom_qty"):
                print(f"  [WARN] {name}: line {line['name']!r} has no "
                      f"quantity in source - line skipped, order still created")
                continue

            product = source.search_read(
                "product.product", [["id", "=", line["product_id"][0]]],
                ["default_code", "name"],
            )[0]
            target_product_id = matcher.match_product(product)
            if not target_product_id:
                print(f"  [FAIL] {name}: product {product['name']!r} not found in target")
                line_error = True
                continue

            uom = source.search_read(
                "uom.uom", [["id", "=", line["product_uom"][0]]], ["name"]
            )[0]
            target_uom_id = matcher.match_uom(uom["name"])

            # Source (v16) field is 'tax_id' - this was fetched above as
            # 'tax_id', so check that same key here (this was previously
            # a bug - 'taxes_id' was checked but never fetched, which
            # would raise a KeyError the moment a line had any tax at all).
            target_tax_ids = []
            if line["tax_id"]:
                taxes = source.search_read(
                    "account.tax", [["id", "in", line["tax_id"]]],
                    ["name", "type_tax_use"],
                )
                for tax in taxes:
                    t_id = matcher.match_tax(tax["name"], tax["type_tax_use"])
                    if t_id:
                        target_tax_ids.append(t_id)

            # Target (v19) field is 'tax_ids' on sale.order.line too.
            line_vals.append((0, 0, {
                "name": line["name"],
                "product_id": target_product_id,
                "product_uom_qty": line["product_uom_qty"],
                "price_unit": line["price_unit"],
                "product_uom_id": target_uom_id or False,
                "tax_ids": [(6, 0, target_tax_ids)],
            }))

        if line_error:
            print(f"  [FAIL] {name}: skipped due to unmatched product(s) above")
            continue

        vals = {
            "partner_id": target_partner_id,
            "client_order_ref": order.get("client_order_ref") or "",
            "date_order": order["date_order"],
            "note": order.get("note") or "",
        }
        if target_currency_id:
            vals["currency_id"] = target_currency_id

        if not apply_changes:
            print(f"  [DRY-RUN] Would create SO {name} "
                  f"(customer={partner['name']}, {len(line_vals)} line(s))")
            continue

        # Create the header first, then add lines one at a time - a
        # single bad line only gets skipped, not the whole order.
        new_id = target.create("sale.order", vals)
        target.execute("sale.order", "write", [new_id], {"name": name})

        added, skipped = 0, 0
        for lv in line_vals:
            try:
                target.execute("sale.order", "write", [new_id], {"order_line": [lv]})
                added += 1
            except xmlrpc.client.Fault as e:
                skipped += 1
                reason = e.faultString.splitlines()[-1] if e.faultString else str(e)
                print(f"  [WARN] {name}: line skipped - {reason}")
                print(f"    Line data: {lv}")

        _copy_attachments(source, target, "sale.order", order["id"], new_id, name)
        status = f"{added} line(s) added" + (f", {skipped} skipped" if skipped else "")
        print(f"  [OK] {name}: created in target as id={new_id} ({status})")



# ============================================================================
# Main
# ============================================================================

def main():
    # When output is piped (e.g. through `tee`), Python fully buffers
    # stdout instead of flushing per-line like it does on a live
    # terminal - meaning any print() still sitting in the buffer at the
    # moment of an unhandled crash can be lost entirely, never reaching
    # the terminal OR the piped file. Force line-buffering so nothing
    # gets silently dropped right before an error.
    sys.stdout.reconfigure(line_buffering=True)

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--apply", action="store_true",
        help="Actually create records in the target (v19) database. "
             "Without this flag, the script only prints what it would do."
    )
    parser.add_argument(
        "--only", metavar="NAME", default=None,
        help="Only process a single record by exact name (e.g. --only P01202). "
             "Useful for testing one record end-to-end before running the "
             "full batch. Matches against either PO or SO names."
    )
    args = parser.parse_args()

    print(f"Mode: {'APPLY (will write to target)' if args.apply else 'DRY-RUN (no changes will be made)'}")

    try:
        source = OdooConnection(**SOURCE, label="source/v16")
        target = OdooConnection(**TARGET, label="target/v19")
    except RuntimeError as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    matcher = RecordMatcher(target)

    po_names = PO_NAMES
    so_names = SO_NAMES
    if args.only:
        po_names = [n for n in PO_NAMES if n == args.only]
        so_names = [n for n in SO_NAMES if n == args.only]
        if not po_names and not so_names:
            print(f"ERROR: --only {args.only!r} does not match any name in "
                  f"PO_NAMES or SO_NAMES.")
            sys.exit(1)

    migrate_purchase_orders(source, target, matcher, po_names, args.apply)
    migrate_sale_orders(source, target, matcher, so_names, args.apply)

    print("\n" + "=" * 70)
    print("SUMMARY")
    print("=" * 70)
    if matcher.unmatched:
        print("Unmatched records requiring manual attention in the target DB:")
        for kind, values in matcher.unmatched.items():
            print(f"  {kind}:")
            for v in sorted(values):
                print(f"    - {v}")
        print(
            "\nCreate/fix these in Odoo 19 first (matching by name/code/VAT "
            "with the source), then re-run this script - it skips orders "
            "that already exist, so it's safe to run again."
        )
    else:
        print("No unmatched partners/products/UoMs/taxes.")

    if not args.apply:
        print("\nThis was a DRY RUN. Re-run with --apply to actually create records.")


if __name__ == "__main__":
    main()